# Generated by Django 5.0.4 on 2025-01-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
